[0m18:15:56.487786 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd3035ce290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd3019f53c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd3019f5360>]}


============================== 18:15:56.490746 | 0745505c-d544-4b7f-b053-0fb66aba5411 ==============================
[0m18:15:56.490746 [info ] [MainThread]: Running with dbt=1.7.8
[0m18:15:56.491429 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/home/vscode/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt init dbt_demo_project', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m18:15:56.491948 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/home/vscode/.dbt')}
[0m18:15:56.492443 [info ] [MainThread]: Creating dbt configuration folder at 
[0m18:15:56.493436 [debug] [MainThread]: Starter project path: /home/vscode/.local/lib/python3.10/site-packages/dbt/include/starter_project
[0m18:15:56.515244 [info ] [MainThread]: 
Your new dbt project "dbt_demo_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:15:56.516368 [info ] [MainThread]: Setting up your profile.
[0m18:19:42.141676 [info ] [MainThread]: Profile dbt_demo_project written to /home/vscode/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m18:19:42.148548 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 225.66638, "process_user_time": 2.179215, "process_kernel_time": 0.159743, "process_mem_max_rss": "109744", "process_in_blocks": "192", "process_out_blocks": "80"}
[0m18:19:42.149235 [debug] [MainThread]: Command `dbt init` succeeded at 18:19:42.149075 after 225.67 seconds
[0m18:19:42.149702 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd3035ce290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd3001558d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd300157730>]}
[0m18:19:42.150190 [debug] [MainThread]: Flushing usage events
[0m18:26:17.967323 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f08144b5ff0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0814b32a10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0814b329b0>]}


============================== 18:26:17.969893 | a6f954ef-b51a-4ca1-b6b6-e024d9be9b09 ==============================
[0m18:26:17.969893 [info ] [MainThread]: Running with dbt=1.7.8
[0m18:26:17.970635 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:26:17.971230 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/drydenne14/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:26:17.972180 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.04686478, "process_user_time": 1.871698, "process_kernel_time": 0.135978, "process_mem_max_rss": "86872", "process_out_blocks": "16", "command_success": false, "process_in_blocks": "0"}
[0m18:26:17.972826 [debug] [MainThread]: Command `dbt run` failed at 18:26:17.972673 after 0.05 seconds
[0m18:26:17.973272 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f08144b5ff0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0814b32aa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0814b329e0>]}
[0m18:26:17.973742 [debug] [MainThread]: Flushing usage events
[0m15:59:14.929594 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7eff87a59ff0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7eff85ed6a10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7eff85ed69b0>]}


============================== 15:59:14.940549 | a34a4346-582c-4718-887d-e7ee7e9db39f ==============================
[0m15:59:14.940549 [info ] [MainThread]: Running with dbt=1.7.8
[0m15:59:14.941225 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/home/vscode/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt test', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:59:14.941795 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/drydenne14/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:59:14.947217 [debug] [MainThread]: Resource report: {"command_name": "test", "command_wall_clock_time": 0.07175001, "process_user_time": 1.961372, "process_kernel_time": 0.190071, "process_mem_max_rss": "86896", "process_in_blocks": "57408", "process_out_blocks": "8", "command_success": false}
[0m15:59:14.948129 [debug] [MainThread]: Command `dbt test` failed at 15:59:14.947905 after 0.07 seconds
[0m15:59:14.948765 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7eff87a59ff0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7eff85ed6aa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7eff85ed69e0>]}
[0m15:59:14.949269 [debug] [MainThread]: Flushing usage events
[0m15:09:37.270260 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa390b1a290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa3911969e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa391196980>]}


============================== 15:09:37.282010 | 927093ca-efab-4504-b379-f8753e1d2d4b ==============================
[0m15:09:37.282010 [info ] [MainThread]: Running with dbt=1.7.8
[0m15:09:37.282926 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt test', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:09:37.283505 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/drydenne14/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:09:37.289117 [debug] [MainThread]: Resource report: {"command_name": "test", "command_wall_clock_time": 0.07536311, "process_user_time": 2.035141, "process_kernel_time": 0.09178, "process_mem_max_rss": "87008", "process_in_blocks": "248", "process_out_blocks": "16", "command_success": false}
[0m15:09:37.289947 [debug] [MainThread]: Command `dbt test` failed at 15:09:37.289734 after 0.08 seconds
[0m15:09:37.290555 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa390b1a290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa391196a70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa3911969b0>]}
[0m15:09:37.291068 [debug] [MainThread]: Flushing usage events
[0m15:15:51.970350 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f139655a290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1394a269b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1394a26950>]}


============================== 15:15:51.981815 | 2dc66e10-c49b-4bfa-8c1f-6e9987805e34 ==============================
[0m15:15:51.981815 [info ] [MainThread]: Running with dbt=1.7.8
[0m15:15:51.982517 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/home/vscode/.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt test', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:15:51.983324 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/drydenne14/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:15:51.988871 [debug] [MainThread]: Resource report: {"command_name": "test", "command_wall_clock_time": 0.07538174, "process_user_time": 1.974038, "process_kernel_time": 0.275264, "process_mem_max_rss": "86820", "process_in_blocks": "57544", "process_out_blocks": "8", "command_success": false}
[0m15:15:51.989861 [debug] [MainThread]: Command `dbt test` failed at 15:15:51.989659 after 0.08 seconds
[0m15:15:51.990334 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f139655a290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1394a26a40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1394a26980>]}
[0m15:15:51.990903 [debug] [MainThread]: Flushing usage events
[0m15:35:57.848187 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f42817cdff0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4281e4a9e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4281e4a980>]}


============================== 15:35:57.850973 | 8ddb4f30-0834-4427-a4cf-75762067f88d ==============================
[0m15:35:57.850973 [info ] [MainThread]: Running with dbt=1.7.8
[0m15:35:57.851653 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m15:35:57.852245 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/drydenne14/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:35:57.853272 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.050343025, "process_user_time": 1.965608, "process_kernel_time": 0.130513, "process_mem_max_rss": "86704", "process_out_blocks": "8", "command_success": false, "process_in_blocks": "0"}
[0m15:35:57.853948 [debug] [MainThread]: Command `dbt run` failed at 15:35:57.853792 after 0.05 seconds
[0m15:35:57.854417 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f42817cdff0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4281e4aa70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4281e4a9b0>]}
[0m15:35:57.854890 [debug] [MainThread]: Flushing usage events
